apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "db-fullname" . }} 
  labels:
    component: "{{ .Release.Name }}-{{ .Values.db.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.db.replicas }}
  selector:
    matchLabels:
      app: {{ template "db-fullname" . }} 
  template:
    metadata:
      labels:
        app: {{ template "db-fullname" . }} 
    spec:
      containers:
      - image: "{{ .Values.db.imageName }}:{{ .Values.db.imageTag }}"
        name: database
        livenessProbe:
          exec: 
            command:
            - sh
            - -c
            - {{ .Values.db.healthcheck.command }}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          exec: 
            command:
            - sh
            - -c
            - {{ .Values.db.healthcheck.command }}
          initialDelaySeconds: 10
          periodSeconds: 15
        env:
        - name: POSTGRES_USER
          value: {{ .Values.db.postgresUser }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.db.postgresPassword }}
        ports:
        - containerPort: {{ .Values.db.containerPort }}
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
        - mountPath: /healthcheck/ 
          name: db-cm 
      volumes:
        - name: db-cm
          configMap:
            name: "{{ template "db-fullname" . }}-cm"
        - name: db-data
  {{- if .Values.db.volumes.enabled }}
          persistentVolumeClaim:
            claimName: "{{ template "db-fullname" . }}-pvc" 
  {{- else }}
          emptyDir: {} 
  {{- end }}
