apiVersion: v1
kind: Service
metadata:
  labels:
    component: "{{ .Release.Name }}-{{ .Values.db.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: database
spec:
  type: {{ .Values.db.serviceType }}
  ports:
  - name: "db-service"
    port: {{ .Values.db.servicePort }}
    targetPort: {{ .Values.db.containerPort }}
  selector:
    app: database 