apiVersion: v1
kind: Service
metadata:
  labels:
    component: "{{ .Release.Name }}-{{ .Values.postgres.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ .Values.postgres.name }}
spec:
  type: {{ .Values.postgres.serviceType }}
  ports:
  - name: "db-service"
    port: {{ .Values.postgres.service.port }}
    targetPort: {{ .Values.postgres.container.port }}
  selector:
    app: {{ .Values.postgres.name }}