apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.postgres.name }} 
  labels:
    component: "{{ .Release.Name }}-{{ .Values.postgres.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.postgres.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.postgres.name }} 
  template:
    metadata:
      labels:
        app: {{ .Values.postgres.name }} 
    spec:
      containers:
      - image: "{{ .Values.postgres.image.name }}:{{ .Values.postgres.image.tag }}"
        name: database
        livenessProbe:
          exec: 
            command:
            - sh
            - -c
            - {{ .Values.postgres.healthcheck.command }}
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          exec: 
            command:
            - sh
            - -c
            - {{ .Values.postgres.healthcheck.command }}
          initialDelaySeconds: 10
          periodSeconds: 15
        env:
        - name: POSTGRES_USER
          value: {{ .Values.postgres.db.user }}
        - name: POSTGRES_PASSWORD
          value: {{ .Values.postgres.db.password }}
        ports:
        - containerPort: {{ .Values.postgres.container.port }}
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-data
        - mountPath: /healthcheck/ 
          name: db-cm 
      volumes:
        - name: db-cm
          configMap:
            name: "{{ .Values.postgres.name }}-cm"
            defaultMode: 0750
        - name: db-data
  {{- if .Values.postgres.volumes.enabled }}
          persistentVolumeClaim:
            claimName: "{{ .Values.postgres.name }}-pvc" 
  {{- else }}
          emptyDir: {} 
  {{- end }}
