{{- if .Values.postgres.volumes.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.postgres.name }}-pvc"
spec:
  accessModes:
    - {{ .Values.postgres.volumes.accessModes }}
  storageClassName: {{ .Values.postgres.volumes.storageClassName }} 
  resources:
    requests:
      storage: {{ .Values.postgres.volumes.size }}
{{- end }}
