apiVersion: v1
kind: Service
metadata:
  labels:
    component: "{{ .Release.Name }}-{{ .Values.redis.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ .Values.redis.name }}
spec:
  type:  {{ .Values.redis.serviceType }}
  ports:
  - name: "redis-service"
    port: {{ .Values.redis.servicePort }}
    targetPort: {{ .Values.redis.containerPort }}
  selector:
    app: {{ .Values.redis.name }}