{{- if .Values.redis.volumes.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "{{ .Values.redis.name }}-pvc"
spec:
  accessModes:
    - {{ .Values.redis.volumes.accessModes }}
  storageClassName: {{ .Values.redis.volumes.storageClassName }} 
  resources:
    requests:
      storage: {{ .Values.redis.volumes.size }}
{{- end }}
