apiVersion: v1
kind: Service
metadata:
  labels:
    component: "{{ .Release.Name }}-{{ .Values.result.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: {{ .Values.result.name }}
spec:
  type: {{ .Values.result.serviceType }}
  ports:
  - name: "result-service"
    port: {{ .Values.result.servicePort }}
    targetPort: {{ .Values.result.containerPort }}
  selector:
    app: {{ .Values.result.name }}
