---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.result.name }}
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: {{ .Values.result.ingress.host }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: result 
            port: 
              number: {{ .Values.result.service.port }}