{{- if .Values.result.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.result.name }}
  labels:
    app: {{ .Values.result.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.result.name }}
  minReplicas: {{ .Values.result.hpa.minReplicas }}
  maxReplicas: {{ .Values.result.hpa.maxReplicas }}
  targetCPUUtilizationPercentage: {{ .Values.result.hpa.targetCPUUtilizationPercentage }}
{{- end }} 

