apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.vote.name }}
  labels:
    component: "{{ .Release.Name }}-{{ .Values.vote.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.vote.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.vote.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.vote.name }}
    spec:
      containers:
      - image: "{{ .Values.vote.image.name }}:{{ .Values.vote.image.tag }}"
        name: vote
        ports:
        - containerPort: {{ .Values.vote.containerPort }}
          name: vote
