apiVersion: v1
kind: Service
metadata:
  labels:
    component: "{{ .Release.Name }}-{{ .Values.vote.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
  name: vote
spec:
  type: {{ .Values.vote.serviceType }}
  ports:
  - name: "vote-service"
    port: {{ .Values.vote.servicePort }}
    targetPort: {{ .Values.vote.containerPort }}
  selector:
    app: vote
