apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "worker-fullname" . }}
  labels:
    component: "{{ .Release.Name }}-{{ .Values.worker.name }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    heritage: {{ .Release.Service | quote }}
    release: {{ .Release.Name | quote }}
spec:
  replicas: {{ .Values.worker.replicas }}
  selector:
    matchLabels:
      app: {{ template "worker-fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "worker-fullname" . }}
    spec:
      containers:
      - image: {{ .Values.worker.imageName }}:{{ .Values.worker.imageTag }}
        name: worker
