project:
  name: voting-app-develop

result:
  name: result
  image:
    name: gonzaloacosta/voting-app-result
    tag: develop 
  replicas: 1
  containerPort: 80
  servicePort: 5001
  serviceType: ClusterIP
  ingressHost: result.develop.192.168.64.6.nip.io
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 60

vote:
  name: vote
  image:
    name: gonzaloacosta/voting-app-vote
    tag: develop
  replicas: 1
  containerPort: 80
  servicePort: 5000
  serviceType: ClusterIP
  ingressHost: vote.develop.192.168.64.6.nip.io
  hpa:
    enabled: true 
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 60

worker:
  name: worker
  image:
    name: gonzaloacosta/voting-app-worker
    tag: develop 
  replicas: 1
  hpa:
    enabled: true 
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 60

postgres:
  name: postgres
  image:
    name: postgres
    tag: 9.4 
  dbUser: postgres
  dbPassword: postgres
  volumes:
    enabled: false
    size: 1G
    accessModes: ReadWriteOnce 
  containerPort: 5432
  servicePort: 5432
  serviceType: ClusterIP
  healthcheck:
    command: /healthcheck/postgres.sh

redis:
  name: redis
  image:
    name: redis
    tag: 5.0-alpine3.10 
  usePassword: false
  volumes:
    enabled: false
    size: 1G
    accessModes: ReadWriteOnce 
  containerPort: 6379
  servicePort: 6379
  serviceType: ClusterIP
  healthcheck:
    command: /healthcheck/redis.sh

#registry:
#  pullSecret: dockerhub
