project:
  name: voting-app-develop

result:
  name: result
  image:
    name: gonzaloacosta/voting-app-result
    tag: pr-1 
  replicas: 1
  container:
    port: 80
  service:
    port: 5001
    type: ClusterIP
  ingress:
    host: result.192.168.64.6.nip.io
  hpa:
    enabled: true
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 60

vote:
  name: vote
  image:
    name: gonzaloacosta/voting-app-vote
    tag: pr-1
  replicas: 1
  container:
    port: 80
  service:
    port: 5000
    type: ClusterIP
  ingress:
    host: vote.192.168.64.6.nip.io
  hpa:
    enabled: true 
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 60

worker:
  name: worker
  image:
    name: gonzaloacosta/voting-app-worker
    tag: pr-1 
  replicas: 1
  hpa:
    enabled: true 
    minReplicas: 1
    maxReplicas: 4
    targetCPUUtilizationPercentage: 60

postgres:
  name: postgres
  image:
    name: postgres
    tag: 9.4 
  db:
    user: postgres
    password: postgres
  volumes:
    enabled: false
    size: 1G
    accessModes: ReadWriteOnce
  container:
    port: 5432
  service:
    port: 5432
    type: ClusterIP
  healthcheck:
    command: /healthcheck/postgres.sh

redis:
  name: redis
  image:
    name: redis
    tag: 5.0-alpine3.10 
  usePassword: false
  volumes:
    enabled: false
    size: 1G
    accessModes: ReadWriteOnce
  container:
    port: 6379
  service:
    port: 6379
    type: ClusterIP
  healthcheck:
    command: /healthcheck/redis.sh

#registry:
#  pullSecret: dockerhub
